spring:
    datasource:
        url: jdbc:mysql://${MYSQL_PORT_3306_TCP_ADDR}:${MYSQL_PORT_3306_TCP_PORT}/${MYSQL_ENV_MYSQL_DB_NAME}?autoReconnect=true
        username: ${MYSQL_ENV_MYSQL_DB_USERNAME}
        password: ${MYSQL_ENV_MYSQL_DB_PASSWORD}
        validation-query: SELECT 1

    jpa:
        hibernate:
            naming:
                implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

logging:
  level:
    org.springframework.security: DEBUG   